name: secure checkout

description: 'secure checkout'

runs:
  using: 'composite'
  steps:
    - name: Checkout the builder
      # TODO: use a secure builder checkout.
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      with:
        fetch-depth: 1
        persist-credentials: false
        # Resolve repo / ref dynamically.
        # Alternative: call the Action with a pin, and adds the pin to the reference release freeze checks:
        # Faster runtime but more maintenance.
        repository: ${{ github.action_repository }}
        ref: ${{ github.action_ref }}
        path: __BUILDER_CHECKOUT_DIR__